name: .NET CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    # Optionally, publish the project
    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./output

    # Optionally, upload artifacts (e.g., for deployment or further use)
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ./output
